export const monthData = {
  Dec: [
    { day: 1, avaliable: false },
    { day: 2, avaliable: false },
    { day: 3, avaliable: false },
    { day: 4, avaliable: false },
    { day: 5, avaliable: false },
    { day: 6, avaliable: false },
    { day: 7, avaliable: false },
    { day: 8, avaliable: false },
    { day: 9, avaliable: false },
    { day: 10, avaliable: false },
    { day: 11, avaliable: false },
    { day: 12, avaliable: false },
    { day: 13, avaliable: false },
    { day: 14, avaliable: false },
    { day: 15, avaliable: true },
    { day: 16, avaliable: true },
    { day: 17, avaliable: true },
    { day: 18, avaliable: true },
    { day: 19, avaliable: true },
    { day: 20, avaliable: true },
    { day: 21, avaliable: true },
    { day: 22, avaliable: true },
    { day: 23, avaliable: true },
    { day: 24, avaliable: true },
    { day: 25, avaliable: false },
    { day: 26, avaliable: false },
    { day: 27, avaliable: true },
    { day: 28, avaliable: true },
    { day: 29, avaliable: true },
    { day: 30, avaliable: true },
    { day: 31, avaliable: false }
  ]
};
